### ISSUE TITLE
default values for editable_labels would be nice

### ISSUE THREAD

**Issue by geisslet** [sapcc/supernova#30]
Reason: would be a kind of templating / and gives just the freedom of change if needed ( a kind of soft fixed value )

**Comment by andypf** [comment]
fixed with #4d2bacb0cdbebdc468c2036c1b0a54047d869309

**Comment by andypf** [comment]
fixed with #34

**Comment by andypf** [comment]
fixed with 4d2bacb0cdbebdc468c2036c1b0a54047d869309

**Comment by andypf** [comment]
fixed with 4d2bacb0cdbebdc468c2036c1b0a54047d869309

**Comment by andypf** [comment]
It is possible now to define default values for editable labels by providing **editable_labels_default_values**
Example: 
  {
    "status": "active",
    "title": "Test",
    "description": "This a test silence template",
    "fixed_labels": {
      "service": "limes",
      "severity": "info"
    },
    "editable_labels": ["region"],
    "editable_labels_default_values": ["eu-nl-1"]
  },
